FROM node:15

#o id já é 1000
USER node 

WORKDIR /usr/src/app


#Ponha os RUN antes de trocar o USER.
  ##WORKDIR vem depois de trocar pois é justamente a pasta que precisamos ter permissões fora do container.